version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vulnerability_scanner_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - vulnerability_network

volumes:
  mongodb_data:
    driver: local

networks:
  vulnerability_network:
    driver: bridge